### ISSUE TITLE
FreeOSEK (CIAA RTOS) indentation is not conform to CIAA Coding Guidelines

### ISSUE THREAD

**Issue by mcerdeiro** [ciaa/Firmware#114]
Indentation in CIAA Firmware is 3 spaces long without tabs.

The complete RTOS is using tabs instead of 3 spaces... :(

The complete Source shall be changed.

**Comment by mcerdeiro** [comment]
Natalia can we close this issue?

**Comment by NataliaRequejo** [comment]
I made a change to replace the tabs in .php files. I think that's all in the RTOS module
