### ISSUE TITLE
Include Freescale KSDK low level driver and connect them to Firmware posix drivers

### ISSUE THREAD

**Issue by apermingeat** [ciaa/Firmware#224]

**Comment by apermingeat** [comment]
Low level driver incorporation already finished for GPIO, ADC, UART. 
Also connection between posix driver and low level driver for GPIO implemented. 
Connection between posix driver and low level driver for ADC and UART is pending.

**Comment by mcerdeiro** [comment]
Can we close this issue, if not please replan for the next release. Thanks

**Comment by mcerdeiro** [comment]
Can we close this issue, if not please replan for the next release. Thanks

**Comment by apermingeat** [comment]
The remaining activities related to this issue is splitted into the next issues and assigned to release 0.5.0:
#233
#234 
#235 
#236 
#237 
#238
