### ISSUE TITLE
review from https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/src/ciaaDriverFlash.c

### ISSUE THREAD

**Issue by mcerdeiro** [ciaa/Firmware#225]
Hola, les dejo algunos comentarios del ciaaDriverFlash.c que me parece se podrian mejorar.

* Las funciones internas pueden (deben) ser declaradas con el prefijo static.
* Faltan comentarios en todos lados... :( Macros, funciones, variables locales, sobre todo si usan 5 o mas y no solo 1 o 2... :)
* en switchs case es buena práctica poner siempre un default
* el default tambien tiene que tener un break al final (https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/src/ciaaDriverFlash.c#L231)
* if con un if se puede remplazar con un if () && (). (https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/src/ciaaDriverFlash.c#L258)
* falta el break: https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/src/ciaaDriverFlash.c#L302
* seek no devuelve la posicion desde el inicio? https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/src/ciaaDriverFlash.c#L305 creo aca se devuelve 0
* en https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/src/ciaaDriverFlash.c#L143
  * data_index debe ser seteada
  * ret no
  * las variables locales es bueno ordenarlas segun su tambanio, primero uint64, luego uint32, luego uin16 luego uint8 (si es uint o int no importa solo el tamanio, para evitar alignment en el stack y perder espacio.  uint8_t buffer[CIAADRVFLASH_BLOCK_SIZE]; deberia ser la última variable. Igual en widnows linux da casi igual, pero en embebidos es una buena rgla a seguir :)
* en https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/src/ciaaDriverFlash.c#L149 se multiplica en vez de usar CIAADRVFLASH_SIZE (https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/inc/ciaaDriverFlash_Internal.h#L91)
* seek (https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/drivers/x86/src/ciaaDriverFlash.c#L285 ) deberia usar off_t y no int32 no?

**Comment by FrancoSalinas** [comment]
https://github.com/ciaa/Firmware/blob/b6b2ce21f0cbc35e98ce209dac645a7dd3f700de/modules/posix/inc/ciaaDevices.h#L116 ciaaDevices usa int32.

**Comment by mcerdeiro** [comment]
tenes razon, es un bug https://github.com/ciaa/Firmware/blob/master/modules/posix/inc/ciaaPOSIX_stdio.h#L262 y https://github.com/ciaa/Firmware/blob/master/modules/posix/src/ciaaPOSIX_stdio.c#L302
usan off_t pero la capa de drivers no... :( yo diria de pasar todo a off_t y el seek convertirlo a lseek? te parece?

**Comment by FrancoSalinas** [comment]
ok, ahora hago el cambio

**Comment by mcerdeiro** [comment]
podemos cerrar la issue? todo resuelto :) ?

**Comment by FrancoSalinas** [comment]
si, todo resuelto
