### ISSUE TITLE
Interrupciones externas y ciaaDriverDio_ioctl

### ISSUE THREAD

**Issue by asCii88** [ciaa/Firmware#272]
Hola, quería saber si se implementara la configuración de interrupciones externas debería hacerse utilizando la función del driver Dio. En ese caso qué literatura o ejemplos me recomendarían seguir para hacerlo de acuerdo al estándar y contribuir en algo.

Gracias.

**Comment by mcerdeiro** [comment]
Hola,

Todavía no hay interrupciones de dio implementadas.

Que es lo que querés hacer? Y vemos si y como se podría implementar en el
firmware. Me parece va a ser complicado. Al menos siguiendo con posix.

Saludos
Mariano
Am 05.06.2015 17:43 schrieb "asCii88" <notifications@github.com>:

**Comment by asCii88** [comment]
Algo muy sencillo: configurar un par de pines para que generen una interrupción en flanco de bajada.

**Comment by mcerdeiro** [comment]
Entiendo. La verdad no se bien. Pero ni es una issue. Asique dirá de
discutirlo en ciaa firmware. Estas en el grupo? La issue la cerraría.

Querés hacerlo en un pin cualquiera o en una entrada de la CIAA-NXP?

Saludos
Mariano
Am 05.06.2015 22:03 schrieb "asCii88" <notifications@github.com>:

**Comment by asCii88** [comment]
No sabía de ese grupo. Cierre nomás

**Comment by mcerdeiro** [comment]
Listado de las listas :

http://proyecto-ciaa.com.ar/devwiki/doku.php?id=docu:intro
Am 06.06.2015 04:47 schrieb "asCii88" <notifications@github.com>:

> No sabía de ese grupo. Cierre nomás
>
> El vie., 5 de junio de 2015 23:38, Mariano Cerdeiro <
