### ISSUE TITLE
add symbol __USE_CMSIS to execute SistemInit() function

### ISSUE THREAD

**Issue by gmuro** [ciaa/Firmware#310]

**Comment by jcecconi** [comment]
Bug is related with startup process:
https://www.lpcware.com/content/faq/how-do-lpcopen-applications-handle-system-startup

if SystemInit is not executed, default oscillator is still running after "startup code" has finished

warn: We need the VTOR initialization for RTOSTESTS

**Comment by mcerdeiro** [comment]
is this issue still open?
