### ISSUE TITLE
improve makefile to avoid kinetis error on opened 0.9.0

### ISSUE THREAD

**Issue by evolentini** [ciaa/Firmware#336]
In a kinetis processor internal flash mut be erased with command "kinetis mdm mass_erase" to avoid problems with security chip's protection. For this very reason if we use "unlock" modifier in "flash write_image" we raise an error on openOCD indicating that the writing of the security bytes it's unsupported.

**Comment by mcerdeiro** [comment]
is this issue still open?

**Comment by mcerdeiro** [comment]
@evolentini: is this issue still open?

**Comment by evolentini** [comment]
Closed
