### ISSUE TITLE
Inline comments with /* */ cause error on generator

### ISSUE THREAD

**Issue by evolentini** [ciaa/Firmware#352]
If a line of oil is comment with /**/ after the statment , this line is ignored without warning or error.

**Comment by cpantel** [comment]
Sorry I can not assert it, my working machine is dead, but I am sure that this case is covered in the test of what I did at line ~76 in https://github.com/ciaa/firmware.modules.rtos/blob/improve_php/generator/tests/utest/OilParserTest.php

**Comment by mcerdeiro** [comment]
@evolentini could you recheck this issue and reopen if needed?
