### ISSUE TITLE
Reference files for rtos osek OilGenerator functional testing drifted

### ISSUE THREAD

**Issue by cpantel** [ciaa/Firmware#382]
The output from OilGenerator has changed and the files used as reference for the funcional testing are no longer valid. Created fix/ftest branch with improved error messages for the ftest

**Comment by jcecconi** [comment]
Consulta..
Cuando un poil se modifica, el generador vuelve a generar los .oil?

**Comment by cpantel** [comment]
No entiendo. ¿qué es un poil?
Lo que si entiendo es que los .oil no se generan, son definiciones de un proyecto, a los cuales OilGenerator usa para generar archivos .c y .h a partir de los templates *.c.php y *_h.php

**Comment by jcecconi** [comment]
Los poil son oil con preprocesamiento, por ejemplo para sacar #ifdef, y
luego se generan los oil para el generate

**Comment by cpantel** [comment]
ok, no hay .poil existentes aun, no? ¿Cuando decís "generan" querés decir "procesan"?

Con respecto a este issue, basta con comentar los "rm ..." en el test y ver si el _Cfg.h o _Cfg.c generado es correcto. De serlo, reemplazar la referencia de modo tal que en la próxima ejecución. Si me validás que son correctos, lo hago yo.

**Comment by cpantel** [comment]
...tal que en la próxima ejecución [no falle]...

**Comment by jcecconi** [comment]
Si correcto, me expresé mal. Los poil se procesan y a partir de ellos se
crean los oil. Acá hay algnos de ejemplo en el que estamos trabajando ahora

https://github.com/ciaa/Firmware/tree/feature/hisio/examples/hisio_example/etc

**Comment by cpantel** [comment]
Ahi corregí los tests, sólo habría que verificar que las referencias en ./generator/tests/ftest/expected sean razonables

**Comment by cpantel** [comment]
Entiendo que lo de los .poil no tienen nada que ver con este issue, cuando haga falta que alguien abra un nuevo issue con ese asunto, por favor
