### ISSUE TITLE
Error al compilar con PHP7

### ISSUE THREAD

**Issue by matiya** [ciaa/Firmware#389]
Tengo:
`PHP Fatal error:  Uncaught Error: Call to undefined function split() in Firmware/modules/rtos/generator/oilParser.php:108`

Lo solucioné reemplazando split() por explode(). Creo que también se puede usar preg_split(), pero no lo probé.

**Comment by pridolfi** [comment]
Issue duplicado. Por favor comentar en https://github.com/ciaa/Firmware/issues/381
