### ISSUE TITLE
update LWIP

### ISSUE THREAD

**Issue by jcecconi** [ciaa/Firmware#391]
update LWIP based on lpcopen 2.16

**Comment by mabeett** [comment]
Please, excuse me for this question, maybe is answered in another place. 
What is necessary for migrating the branch `feature/ethernet` onto `master` and the releases?
Thanks

**Comment by mcerdeiro** [comment]
We are still working on some needed features for lwip. In an other branch
we are implementing a simulation of semaphore and sleep in osek
environment. These features are needed to complete de port of lwip and to
merge it to the master.
Am 05.06.2016 12:29 AM schrieb "MAbeeTT (Matías Pecchia)" <
notifications@github.com>:
