### ISSUE TITLE
ciaaPOSIX_usleep no toma valores menores a 1000000?

### ISSUE THREAD

**Issue by m4v** [ciaa/Firmware#417]
En https://github.com/ciaa/Firmware/blob/master/modules/posix/inc/ciaaPOSIX_unistd.h#L86 dice
> \param[in] useconds micro seconds to sleep the application. Value shall be between 0 and 1000000.

valor correcto desde 0 a un millón, ok. Pero en https://github.com/ciaa/Firmware/blob/master/modules/posix/src/ciaaPOSIX_unistd.c#L146 tiene un check que retorna -1 si es menor a 1000000. Sospecho un error en el if, pero al mismo tiempo veo que los test unitarios en verifican justamente eso https://github.com/ciaa/Firmware/blob/master/modules/posix/test/utest/src/test_ciaaPOSIX_unistd.c#L443 algo menor a 1000000 debe retornar error.

Ya en este punto estoy completamente confundido sobre lo que se supone que usleep debe hacer.

**Comment by mcerdeiro** [comment]
Suena razonable y parece ser un error. El finde miro tu propuesta y la
mergeo. :)

Saludos
Mariano
Am 23.06.2016 9:39 PM schrieb "Elián Hanisch" <notifications@github.com>:

**Comment by jcecconi** [comment]
Hay que ver bien el tema los utest cuando hay #if que modifican el código.
Entiendo que se debería hacer similar a como es en el rtos donde hay varios
test que definen lo necesario para probar todas las variantes de código.
Porque en este caso pasó el utest justamente porque el problema estaba
dentro de un #if no compilado

**Comment by mcerdeiro** [comment]
Creo que podemos cerrar esta issue, no?
